### ISSUE TITLE
passReqToCallback missing in docs

### ISSUE THREAD

**Issue by fmalk** [jaredhanson/passport-local#101]
I was reading http://passportjs.org/guide/username-password/ and stuck trying to send domain info along my custom `LocalStrategy`, and only by looking at source code I found the `passReqToCallback` feature.
Page guide should be updated to document it.

**Comment by GochoMugo** [comment]
Yeah it should. A pull request?

**Comment by fmalk** [comment]
Will do.

**Comment by fmalk** [comment]
Couldn't find how to edit passportjs.org directly, so I've updated `passport-local` README.md

**Comment by GochoMugo** [comment]
:+1: That's just awesome
