### ISSUE TITLE
Password field 'safe' in mongoose

### ISSUE THREAD

**Issue by Evanion** [jaredhanson/passport-local#108]
Hello
It doesn't seem like passport-local is able to validate the password, when the field is marked as 'safe' in the schema, as soon as we remove the 'safe' tag, the validation works. Are we missing some configuration in passport-local to make it specifically request that field from mongoose?

**Comment by jaredhanson** [comment]
`passport-local` does not validate passwords.  It invokes the `verify` callback that your applications supplies.  If this is an issue, it is with application-provided code, not this package.
