### ISSUE TITLE
Error: Unknown task "default"

### ISSUE THREAD

**Issue by blrenky** [jaredhanson/passport-local#111]
david@Cloud1:/home/core/jake$ jake
jake aborted.
Error: Unknown task "default"
    at TaskBase.nextPrereq (/usr/lib/nodejs/jake/task/task.js:141:15)
    at TaskBase.runPrereqs (/usr/lib/nodejs/jake/task/task.js:116:12)
(See full trace by running task with --trace)
david@Cloud1:/home/core/jake$ sudo make install
/bin/sh: 4: npm: not found
Makefile:29: recipe for target 'install' failed
make: *** [install] Error 127
david@Cloud1:/home/core/jake$ ls
bin           docs  jake.bat  lib      Makefile      package.json  site
changelog.md  jake  Jakefile  LICENSE  node_modules  README.md     test
david@Cloud1:/home/core/jake$ jake -f db/seed.js seed
jake aborted.
Error: No Jakefile. Specify a valid path with -f/--jakefile, or place one in the current directory.
    at api.fail (/usr/lib/nodejs/jake/api.js:326:18)
    at EventEmitter.utils.mixin.run (/usr/lib/nodejs/jake/jake.js:317:9)
(See full trace by running task with --trace)
david@Cloud1:/home/core/jake$

Iam unable to install Jake on debian os, please check this error.

**Comment by jaredhanson** [comment]
Closing.  This has nothing to do with this project.
