### ISSUE TITLE
Return HTTP code instead of redirect

### ISSUE THREAD

**Issue by DaAwesomeP** [jaredhanson/passport-local#113]
I have an AJAX-based login form, and having a failed username/password simply giving me the output in HTML of my login page is useless. Is there a way to have it return `401` when the username/password fails and `200` when it is correct?

**Comment by DaAwesomeP** [comment]
I found that removing the options object will cause it to return `401` as I want it to when it fails, but it returns `404 on success. It is still trying to redirect somewhere.

**Comment by DaAwesomeP** [comment]
Nevermind. I used `compose` to get it to work.

**Comment by jaredhanson** [comment]
Could you provide an example for others who might find your solution useful?

**Comment by DaAwesomeP** [comment]
This is what works for me:
```javascript
router.post('/login', compose([
  passport.authenticate('local'),
  function*(){
    // This function will not run if the login fails. If it fails, the response code will be 401 and the response body will be 'Unauthorized'
    // The response HTTP code will be 200 unless changed in this function.
    this.body = 'Login was successful!';  // Response body sent
    //this.status = 200;                  // Uncomment to change the status. 200 is sent by default.
  }
]));
```
However, I use `koa-ensure-login` too, so I wanted to keep the redirect after login:
```javascript
router.post('/login', compose([
  passport.authenticate('local'),
  function*(){
    var responseJSON = {};
    if (this.session.returnTo) responseJSON.returnTo = this.session.returnTo;
    else responseJSON.returnTo = false;
    this.body = responseJSON;
  }
]));
```
If the `returnTo` variable is in the session, then it will pass it in the form of JSON to my AJAX on the other end which will do a JavaScript redirect from there. I had to add `this.session.returnTo = null;` to my logout function (or it would be persistent even after logout). That way if you go directly to the login page, then it won't redirect you anywhere. You could also just use a GET variable on the login page, but this is less work.
