### ISSUE TITLE
registering user

### ISSUE THREAD

**Issue by dhamilton1963** [jaredhanson/passport-local#126]
I'm wanting to create a type of user (i.e. employee). How should I go about this? I'm thinking the register form would need to have fields to support user portion (username, email, password), plus additional fields for employee. In the Employee.create I would need to call a passport local method to register the user, then continue and add the employee. But what method should be called and what is the syntax? I'm using Sails-js, Passport-js and Passport-Local.

Thanks

**Comment by jaredhanson** [comment]
Passport doesn't provide anything in the way of registering a user.  You use Passport to authenticate users after they have signed up.
