### ISSUE TITLE
Middleware chain ended by library.

### ISSUE THREAD

**Issue by Freyert** [jaredhanson/passport-local#131]
Hey @jaredhanson ,

Love `passport`, it's so nice having a single way of doing things. However, I'm running into issues because passport kills the middleware chain in a few cases. I've noticed this on errors, and redirects. This behavior is good for the novice because it protects them from some serious errors, but it really gets in the way after you've gotten your head around middleware.

I'm guessing this all happens inside the default [`authenticate`](https://github.com/jaredhanson/passport/blob/master/lib/middleware/authenticate.js#L57) at the [`complete`](https://github.com/jaredhanson/passport/blob/master/lib/middleware/authenticate.js#L238-L251) function because it `returns` after calling `res.redirect` instead of going all the way down and calling `next()` which should be `return next()`. 

This would be a gimongously backwards incompatible change and this _might_ be bike shedding on my part. And it seems like the good work around is to pass a `callback` to the `authenticate` function in order to steer custom functionality.

**Comment by jaredhanson** [comment]
In what case would a redirect continue the middleware chain?  A redirect sends a response, thus ending it.  I'm not sure when it would be considered useful to continue request processing after a response has been sent.

The `failWithError` option is used to tell passport to trigger error handling middleware on authentication failures, rather than an immediate `401` response.

**Comment by Freyert** [comment]
Well my use case is I want a log of all the In and Out from the server. If passport redirects without continuing the chain I won't be able to collect a record that I redirected that user. I use this pattern quite frequently as it eliminates the need to do inline logging.

**Comment by jaredhanson** [comment]
Don't use `successRedirect`, and let it fall into the next middleware, log and redirect yourself.  Would that work?

**Comment by Freyert** [comment]
Ah, sounds interesting. I'll take a peek at that. Do you think it would be viable in the future to create an option that forces middleware continuation on errors/redirects? I'd be happy to work out a PR when I get the time. (And are those the only times `passport` ends middleware chains?) Something along the line of `next: [ 'onError', 'onRedirect']`?

**Comment by Freyert** [comment]
Also, apologies for opening the issue in passport-local, I meant it to go in the main passport repo. I'm working with the `passport-oauth2`, but the issue is in the underlying `passport` library's redirect function.

**Comment by Freyert** [comment]
#458 is the possible solution?
