### ISSUE TITLE
Allow usernameField and passwordField to be object properties

### ISSUE THREAD

**Issue by vinaygopinath** [jaredhanson/passport-local#136]
I'm trying to use passport-local when the request JSON is structured like this
```json
{
  "user": {
    "name": "ABC",
    "password": "xxxxxx",
    "email": "DEF"
  },
  "someOtherObject": {
  }
}
```

The `util.lookup` function expects the `usernameField` and `passwordField` fields to be available in the request body, so specifying the values as `user.name` and `user.password` does not work. Is there a way to achieve this?

If you're open to it, I can modify util.js to use a new `userObject` param that controls the fields lookup (req.body.user instead of req.body, for example).
```
passport.use(new LocalStrategy({
    usernameField: 'email',
    passwordField: 'password',
    userObject: 'user'
  }
));
```

**Comment by jaredhanson** [comment]
Feel free to fork this and maintain such functionality separately.  Most people don't need this functionality, and I don't want to maintain the additional complexity here, especially when it would be unnecessary in most cases.

**Comment by vinaygopinath** [comment]
Thanks for the quick response. I was nearly done adding the `userObject` param in my fork when I went through your tests and noticed that this feature is already supported using object notation.

If anyone else is looking to use an object for the user fields, this works:
```javascript
passport.use(new LocalStrategy({
    usernameField: 'user[email]',
    passwordField: 'user[password]'
  }
));
```
