### ISSUE TITLE
Only throw 'Missing credentials' if actually missing

### ISSUE THREAD

**Issue by wbw** [jaredhanson/passport-local#14]
Hi,

Currently the 'Missing credentials' (BadRequestError) also gets thrown on empty username or password instead of only 'undefined' username or password. This results in a thrown error on an empty login form submit (with a fixed message in a language my application doesnt support).

Why not only throw on actually missing username or password fields in the body? And pass them along to the 'verify' even if empty and let the verify call handle the check (which will not find anything, since the username/password are empty) and return a proper error message (which can than be in any language I want).

Regards,
Wytze

**Comment by bilalyaqoob** [comment]
i have the same issue i know where the error is coming when i provide credentials i used email instead of username plz tell me how i add email instead of username
