### ISSUE TITLE
Nested email and password fields

### ISSUE THREAD

**Issue by davidalekna** [jaredhanson/passport-local#160]
Hi! I'm having trouble to nest email and password fields. As I'm tied up with existing user schema email is under emails: [ { address: '...' } ] and pass is under services: { password: { bcrypt: '...' } }, also my LocalStrategy is not in a callback, so I cannot access req props. I've tried following approach 

```
new LocalStrategy({
    usernameField: 'emails[0].address',
    passwordField: 'services.password.bcrypt'
  }, () => {})
```

but no luck... Any advice on that would be appreciated! Thanks

**Comment by EmiPhil** [comment]
For a schema that looks like

```js
{
  emails: [
    { address: 'x' }
  ],
  services: {
    password: {
      bcrypt: '...'
    }
  }
}
```

the strategy should look like:

```js
new LocalStrategy({
    usernameField: 'emails[]0[]address',
    passwordField: 'services[]password[]bcrypt'
  }, () => {})
```

Play with the [lookup function](https://github.com/jaredhanson/passport-local/blob/master/lib/utils.js) to get a better feel for how it works

**Comment by davidalekna** [comment]
Thanks!
