### ISSUE TITLE
cannot run npm test

### ISSUE THREAD

**Issue by not-varram** [jaredhanson/passport-local#184]
here is the error code and what i typed

C:\Users\hemas\Documents\varcoding\auth test passport\passport-local>npm test

> passport-local@1.0.0 test C:\Users\hemas\Documents\varcoding\auth test passport\passport-local 
> make test

process_begin: CreateProcess(NULL, which jsdoc mr-doc, ...) failed.
make: node_modules/make-node//lib/doc.mk:15: pipe: No error
process_begin: CreateProcess(NULL, which jsdoc mr-doc, ...) failed.
make: node_modules/make-node//lib/doc.mk:17: pipe: No error
process_begin: CreateProcess(NULL, which mocha vows, ...) failed.
make: node_modules/make-node//lib/test.mk:15: pipe: No error
process_begin: CreateProcess(NULL, which mocha vows, ...) failed.
make: node_modules/make-node//lib/test.mk:17: pipe: No error
process_begin: CreateProcess(NULL, which istanbul jscoverage, ...) failed.
make: node_modules/make-node//lib/cov.mk:15: pipe: No error
process_begin: CreateProcess(NULL, which istanbul jscoverage, ...) failed.
make: node_modules/make-node//lib/cov.mk:18: pipe: No error
process_begin: CreateProcess(NULL, which jshint jslint, ...) failed.
make: node_modules/make-node//lib/lint.mk:15: pipe: No error
process_begin: CreateProcess(NULL, which jshint jslint, ...) failed.
make: node_modules/make-node//lib/lint.mk:17: pipe: No error
"No program to make target 'test'. Stop."
""
"The target 'test' can be enabled by installing mocha:"
"  npm install -g mocha"
""
"If mocha is installed locally, try this instead:"
"  npm test"
process_begin: CreateProcess(NULL, false, ...) failed.
make (e=2): The system cannot find the file specified.
make: *** [node_modules/make-node//lib/test/notfound.mk:10: test] Error 2
npm ERR! Test failed.  See above for more details.

**Comment by VarshithSatti** [comment]
did i do any thing wrong pls help me!!

**Comment by VarshithSatti** [comment]
i tried 
npm install -g mocha
