### ISSUE TITLE
Getting a lot of 410 again **Progress Issue**

### ISSUE THREAD

**Issue by mh4ck** [jaredhanson/passport-local#192]
Hi, 

once a month i get a ton of 410 responses while requesting the video info so i decided to go deeper in it now and find a way to solve it.

So my steps i do now: 

1. Identify the/a proxy that get a 410 eveytime
2. Identify a video with response is 410
3. Try to download it with that proxy over youtube-dl to check if they have a way to work around

So i identified everything and found out that youtube-dl can download the video with that proxy but it seems to also not work at the first endpoint they use. The output is: 

```
[youtube] ET0Oy90Xj58: Downloading webpage
WARNING: Unable to download webpage: HTTP Error 429: Too Many Requests
[youtube] ET0Oy90Xj58: Downloading API JSON
[youtube] ET0Oy90Xj58: Downloading API JSON
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on 'https://rr3---sn-t0a7sn7d.googlevideo.com/...
```

and then it starts the download.

ytdl-core with the following code just throws a 410
```
const ytdl = require("ytdl-core");
const HttpsProxyAgent = require("https-proxy-agent");

const username = "...";
const password = "!...*";

const agent = new HttpsProxyAgent(
  `http://${username}:${password}@...:....`
);

ytdl
  .getInfo("ET0Oy90Xj58", {
    requestOptions: {
      agent: agent
    },
  })
  .then((info) => {
    console.log(info);
  })
  .catch((err) => {
    console.log(err);
  });
```

I am not into the ytdl-core code completly so i am now starting to figure out which endpoints ytdl-core is using and which youtube-dl use. 

If somebody wanna help me add me in discord: NoInfo#7031
I will send you the proxy (private proxy) i'm using.

I hope we will figure out the problem to make this package even better and make it a woth competitor to youtube-dl.

**Comment by jaredhanson** [comment]
It's unclear why you are filing this issue against `passport-local`.  Do you have the wrong repository?
