### ISSUE TITLE
Allow passport to return authentication failure messages via variable

### ISSUE THREAD

**Issue by EvHaus** [jaredhanson/passport-local#4]
As per my discussion with Jared via IM, this issue is to require the ability to pass back authentication failure messages to the passport.authenticate function. Perhaps via:

passport.authenticate(... func(err, user, info))

The issue right now is that there is no good way to return back an error message from the LocalStrategy. The only option is to either return a server failure via 'err' which will cause the server to simply return a 500 HTTP error, or to use a workaround which uses the user object to return back the error message.

As a result, the done function will probably look something more like this:

done(null, false, 'bad password')

Here is a jsfiddle where I'm running into the issue. In this example, the server simply returns a 500 error for all failures -- and I want it to return an error string instead:

http://jsfiddle.net/nd8LZ/1/

**Comment by Zane-XY** [comment]
What's the point of using `flashMessage`  `failureRedirect` here? The way how to show the errors varies from case to case,  and why can't we just use a callback function to deal with it whatever makes sense?

**Comment by wwiatt** [comment]
Has anyone implemented sending a flash message and not redirecting?  I am doing login through a modal and cannot seem to avoid the redirect made from the post to my local-login strategy?

**Comment by marcogreselin** [comment]
How can I return multiple messages, for instance if the login fails I want to return an appropriate error message and the email that was entered so I can feed the email input again.

    done(null, false, { message: 'bad password', email: emailVariable});

This does not work.

**Comment by GEOLYTIX** [comment]
@silps 

`req.session.messages = [];`

What is this supposed to do? Resetting the session messages? I don't think this will work.

I just display the last of the messages in the array. Like so in EJS:

`        <% if (login_errors.length > 0) { %>
            <%= login_errors[login_errors.length -1]%><br>
        <% }%>`

`

**Comment by silps** [comment]
@GEOLYTIX yes, this approach will work also, it's just that each time I refreshed the site there was one more of the same message in the array, so I cleaned it each time, but your way also works

**Comment by riclf** [comment]
@jaredhanson I have a programming situation where I want to know if the user exists, because I am gong to take different application action based on if they already exist or not. So I wish there would be a passport.js URL to provide support for /exist , where I provide a username and passport returns a 0 or 1. Ok, this is not available. So I post to /login with a username and password. The password can be anything. In the passport.use function if the username is not found I return-

        if (!user) {
            return done(null, false, { "rtnCode": 1 });    // user not found, user doew not exist
        }

If the user was found I instead return-
          return done(null, false, { "rtnCode": 2 });    // user was found, user exists

Now, in passport.authenticate('local-login', function(err, user, info) 
info will contain either { "rtnCode": 1 } or { "rtnCode": 2 }

That means that in 
			// incorrect Username or password
			if (!user) {
			    //return res.redirect('/auth/login');	  // as per passport.js example
			    return res.json(info);  			 // rtn code- { "rtnCode": 1 } or { "rtnCode": 2 }
                                                                                         // user does not exist, or does exist
			}
Now I can send a specific return code to my app which provides me the information that the user exists or not.  Here is the problem. Even though the execution flow ends with a return and so does not ever run-
      req.logIn(user, function(err)

If I now issue an ajax GET with the username that I know exists and a bogus password, I get in, I am able to read the database.

That is very unexpected as I have never issued req.logIn(). And of course it is a security issue.  The point here is that upon a "bad" username or password in my /login I do not want to go to a webpage, I want to take a different course of action in code.

**Comment by Gilbert136** [comment]
Im using angular4 with passport, is there anyway i can get res without the redirect feature in passport?

**Comment by Gilbert136** [comment]
So it happens that passport has a function to do solve that in their documentation, 
A section call custom callback helped me solved it

**Comment by banyustudiodev** [comment]
//routes examples
`router.get('/', function (req, res, next) {
  res.render('administrator/login', {
    title: 'Login Admin',
    alerts: req.flash()
  });
});`


//ejs handler
`<% if (alerts.error) { %>
<% alerts.error.forEach(function(msg) { %>
<div class="alert alert-danger"><%= msg %></div>
<% }); %>
<% } %>
<% if (alerts.success) { %>
<% alerts.success.forEach(function(msg) { %>
<div class="alert alert-success"><%= msg %></div>
<% }); %>
<% } %>`

**Comment by itsgracian** [comment]
thanks @jaredhanson !! you saved me hhhh

**Comment by godmar** [comment]
There is abundant confusion on the web regarding how the information passed as `info` to the verify callback is being used, e.g. [here](https://stackoverflow.com/questions/27961137/how-to-passing-message-to-client-in-passportjs).  The main issue that confuses people is that the following does not work:

```
const express = require('express');
const app = express();
const passport = require('passport');
const { Strategy: LocalStrategy } = require('passport-local');

app.use(express.json());

passport.use(new LocalStrategy({ failWithError: true },
    (username, password, cb) => {
        console.log(`executing local strategy ${username} and ${password}`);
        // user expects 'message: `user not found`' to be forwarded to the 
        // client along with the 401 Unauthorized response
        cb(null, false, { message: `user not found` });
    })
);

app.post('/login', passport.authenticate('local', { session: false }))

app.listen(3000, () => {
  console.log(`Run:`);
  console.log(`curl -v --header "Content-Type: application/json" -d '{"username":"dauser","password":"dapass"}' -X POST http://localhost:3000/login`);
});
```

In other words, the default action of the passport-local middleware is to ignore what's being passed to `verify(null, false, info)` in the `info` slot, unless the user invokes the middleware function produced by passport.authenticate() directly via `passport.authenticate(...)(req, res, next)` and sends the response themselves. @jaredhanson [comment from 2012](https://github.com/jaredhanson/passport-local/issues/4#issuecomment-4529009) seems to indicate that this is the desired behavior, at least as of 2012.

This confuses users who expect to use passport.authenticate() as middleware before their own request handlers.

Exacerbating the matter is the fact that passport.authenticate takes [several options](https://github.com/jwalton/passport-api-docs#passportauthenticatestrategyname-options-callback), none of which have the desired behavior of passing along the information to the client.

I'm wondering if this could/should be revised. It seems, to me, a perfectly established pattern to - by default - take the object passed as `info` and send it as a JSON body to the client in the response. If not by default, an option `sendErrorInfoToClient` could be provided. Or am I wrong, and it's best practice to not send anything with a 401?

**Comment by mattcarlotta** [comment]
It's been 8 years and I don't think this feature will ever get implemented. That said, you can create a **workaround** to keep the strategy as a middleware function and still have custom messages sent back to the client (and the function can be made reusable for other controllers if desired):

**Express route:**
```
const { login } = require("../controllers/login)";
const localLogin = require("../services/strategies)";

module.exports = app => {
  app.post("/api/login", localLogin, login);
};
```

**Passport Middleware**

```
const bcrypt = require("bcryptjs");
const passport = require("passport");

// reusable func to return errors to client
const sendError = (err, res) => res.status(400).json({ err: err.toString() });

const badCredentials = "There was a problem with your login credentials. Please make sure your username and password are correct.";

passport.use(
  "local-login",
  new LocalStrategy(
    {
      usernameField: "email",
      passwordField: "password",
      passReqToCallback: true,
    },
    async (req, email, password, done) => {
      try {
        // check to see if the user already exists
        const existingUser = await User.findOne({ email });
        if (!existingUser) return done(badCredentials, false);

        // compare password to existingUser password
        const validPassword = await bcrypt.compare(
          password,
          existingUser.password,
        );
        if (!validPassword) return done(badCredentials, false);

        return done(null, existingUser);
      } catch (err) {
        return done(err, false);
      }
    },
  ),
);

// exporting a wrapper function that will invoke the passport.authenticate method
module.exports = (req, res, next) => {
  const { email, password } = req.body;

  // if email or password are missing, send an error back to the client
  if (!email || !password) return sendError(badCredentials, res);

  passport.authenticate("local-login", (err, user) => {
    // if an error was returned by the strategy, send it to the client
    if (err) return sendError(err, res);
   
    // manually setting the logged in user to req.user 
    // optionally, you can set it to "req.session" if you're using some sort of session
    req.user = user;

   // invoking "next" to continue to the controller
    next();
  })(req, res, next);
};
```

**Express Controller**

```
exports.login = (req, res, done) => {
  // do any additional aggregation with "req.user"

  res.status(201).json({ ...req.session, ...etc });
};
```

The biggest advantage of this approach is that you can now unit test the authenticate strategy separately from the controller. The disadvantage is that this still doesn't support passport sessions (which doesn't appear to be supported when utilizing any custom callbacks).

**Comment by vigansokoli** [comment]
> 
> 
> It's been 7 years and I don't think this feature will ever get implemented. That said, you can create a **workaround** to keep the strategy as a middleware function and still have custom messages sent back to the client (and the function can be made reusable for other controllers if desired):
> 
> **Express route:**
> 
> ```
> const { login } = require("../controllers/login)";
> const localLogin = require("../services/strategies)";
> 
> module.exports = app => {
>   app.post("/api/login", localLogin, login);
> };
> ```
> 
> **Passport Middleware**
> 
> ```
> const bcrypt = require("bcryptjs");
> const passport = require("passport");
> 
> // reusable func to return errors to client
> const sendError = (err, res) => res.status(400).json({ err: err.toString() });
> 
> const badCredentials = "There was a problem with your login credentials. Please make sure your username and password are correct.";
> 
> passport.use(
>   "local-login",
>   new LocalStrategy(
>     {
>       usernameField: "email",
>       passwordField: "password",
>       passReqToCallback: true,
>     },
>     async (req, email, password, done) => {
>       try {
>         // check to see if the user already exists
>         const existingUser = await User.findOne({ email });
>         if (!existingUser) return done(badCredentials, false);
> 
>         // compare password to existingUser password
>         const validPassword = await bcrypt.compare(
>           password,
>           existingUser.password,
>         );
>         if (!validPassword) return done(badCredentials, false);
> 
>         return done(null, existingUser);
>       } catch (err) {
>         return done(err, false);
>       }
>     },
>   ),
> );
> 
> // exporting a wrapper function that will invoke the passport.authenticate method
> module.exports = (req, res, next) => {
>   const { email, password } = req.body;
> 
>   // if email or password are missing, send an error back to the client
>   if (!email || !password) return sendError(badCredentials, res);
> 
>   passport.authenticate("local-login", (err, user) => {
>     // if an error was returned by the strategy, send it to the client
>     if (err) return sendError(err, res);
>    
>     // manually setting the logged in user to req.user 
>     // optionally, you can set it to "req.session" if you're using some sort of session
>     req.user = user;
> 
>    // invoking "next" to continue to the controller
>     next();
>   })(req, res, next);
> };
> 
> // alternatively, you can use a promise as well...
> module.exports = async (req, res, next) => {
>   const { email, password } = req.body;
> 
>   if (!email || !password) return sendError(badCredentials, res);
> 
>   try {
>     const user = await new Promise((resovle, reject) => {
>       passport.authenticate("local-login", (err, user) =>
>         err ? reject(err) : resolve(user),
>       )(req, res, next);
>     });
> 
>     req.user = user;
>     next();
>   } catch (err) {
>     return sendError(err, res);
>   }
> }
> ```
> 
> **Express Controller**
> 
> ```
> exports.login = (req, res, done) => {
>   // do any additional aggregation with "req.user"
> 
>   res.status(202).json({ ...req.user, ...etc });
> };
> ```
> 
> The biggest advantage of this approach is that you can now unit test the authenticate strategy separately from the controller. The disadvantage is that this still doesn't support passport sessions (which doesn't appear to be supported when utilizing any custom callbacks).

Thank you, this was very useful and clean.
