### ISSUE TITLE
Can not work with restify when posting parameters

### ISSUE THREAD

**Issue by hilr** [jaredhanson/passport-local#48]
I use restify as the server and use passport and passport-local to do authentication with username and password. However I always get 401 response. I checked the payroll, it is correct. Then I checked passport-local, it is incompatible with restify when using post method.
Here is the problem in  passport-local / strategy.js line 92
in function lookup(), the req.body passed in from restify is a string, not an object. So when passing the parameters in post body, it goes wrong.

**Comment by jaredhanson** [comment]
According to [this comment](https://github.com/jaredhanson/passport-local/pull/55#issuecomment-51103277), restify can parse into req.body. Since that's the dominant convention in the Node community as a whole, that's what Passport supports.
