### ISSUE TITLE
Error running express3-mongoose-multiple-files

### ISSUE THREAD

**Issue by oakley808** [jaredhanson/passport-local#74]
Hi.
The example "express3-mongoose-multiple-files" doesn't run for me on OSX. I get the following error
```shell
examples/express3-mongoose-multiple-files/config/pass.js:40
  console.log(req.user);
                 ^
TypeError: Cannot read property 'user' of undefined
...
```
Maybe app needs to be passed to pass.js for req to be defined?
The express3-mongoose example seems to work fine.

(I'm using Express 3 and Node v0.10.26)

**Comment by jaredhanson** [comment]
To reduce the noise of issues filed against examples, I'm moving examples to separate repositories. Please feel free to take ownership of this example by creating a new repo and adding it to the wiki here: https://github.com/jaredhanson/passport-local/wiki/Examples
