### ISSUE TITLE
Prevent deserialize to lookup in the DB at each request

### ISSUE THREAD

**Issue by kstankov** [jaredhanson/passport-local#96]
Hi,
sorry to post this as an issue, as it is more likely to be a question, but I'm having hard time finding the answer.
I based my implementation on the example here: 
https://github.com/jaredhanson/passport-local/blob/master/examples/express3/app.js

Everything works fine with Local Strategy (using CouchDB), until it comes to calling req.isAuthenticated() at each request.

It calls then passport.deserializeUser(function(id, done) {...} where I'm supposed to get again the user from the DB. 

This seems a huge overload - may be I misunderstand, but I expected that the authentication will be based on data in the session, not on checking the user each time against the DB.
Is this by design, or I misunderstand something?
Thanks a lot in advance!

**Comment by kstankov** [comment]
Ok, I understood it finally. If I only want to store the ID of the user, I can omit call to the DB.
But why isn't there a way just to copy the user from req to res, without calling deserialize, where I need to read the DB to retrieve again the user info I need in the session...

passport.deserializeUser(function(id, done) {
        console.log("[deserializeUser] id " + id);
        done(null, {user:id});
        /*
         reading from db...
        */
    });

**Comment by jaredhanson** [comment]
You can serialize the whole user object to avoid DB calls on each request.  It is left up to your application to decide what the best implementation is.
