### ISSUE TITLE
Always return "missing credentials"

### ISSUE THREAD

**Issue by msdark** [jaredhanson/passport-local#97]
This is my implementation with coffeescript and Express 4

    passport.use new LocalStrategy
       usernameField:'emailAddress'
    ,(username,password,done) ->
       console.log('credentials passed to passport' + username + '' + password)

      User.findOne emailAddress:username,(err,user) ->
        if err then return done(err)
        if not user
          return done(null,false,message:'Incorrect data')
        bcrypt.compare password,user.password, (err,isMatch) ->
          if err then return done(err)
          if isMatch then return done(null,user)
          else return done(null,false,message:'Incorrect data')

    #Authenticate user
    app.post '/api/v1/auth/login',(req,res,next) ->
      passport.authenticate('local',(err,user,info) ->
        error = err or info
        if error then return res.status(400).json {user:null,state:'failure',error:error}
        req.logIn user,(err) ->
          if err then return res.status(400).json {user:null,state:'failure',error:err}
          res.status(200).json {user:req.user,state:'success'}
      ) req,res,next

I'm also using a linkedIn-strategy

I testing with an angular app and also with

     curl -v -d '{"emailAddress":"test@test.cl","password":"test"}' http://127.0.0.1:8070/api/v1/auth/login --trace-ascii /dev/stdout -H "Content-Type: application/json"

But I only get this

    {"user":null,"state":"failure","error":{"message":"Missing credentials"}}

can you see the problem?

**Comment by xpepermint** [comment]
I have similar issue. `new LocalStrategy` never gets called.

**Comment by GochoMugo** [comment]
Is your request body being parsed?

**Comment by sirkitree** [comment]
my problem was not including the body-parser middleware. Thanks for the hint @GochoMugo

**Comment by jaredhanson** [comment]
Answered by @GochoMugo. Closing.

**Comment by the1mills** [comment]
ughhh I thought the authentication info was in req.headers not req.body...

**Comment by shoaibnoor95** [comment]
hey i have bodyParser in my app.js but still getting the same message why???

**Comment by mjmnagy** [comment]
@shoaibnoor95 same issue here

`passport.authenticate('bush', function(err, user, info) {...`
`console.log(user, err, info, req.body);`

i get
`false null { message: 'Missing credentials' } { email: 'my email', passwod: 'passs' }`

in my local strategy, i placed another console.log to see if its even being touched and it yields nothing

**Comment by haidarIqbal** [comment]
> [``](**### 

- [ ] @ #1. url

**)

**Comment by haidarIqbal** [comment]
i got my issue solved by replacing "email" with "username" in all files.

**Comment by abayoss** [comment]
_i do not know if it would be helpful to somebody but_ : i solved the same problem by **checking the password input name** , it had a capital P !

**Comment by batrasagar** [comment]
Mee too, resolved by Password -> password

**Comment by vickyktk** [comment]
yes the password  changing did worked for me. from P to p

**Comment by mansoor-omrani** [comment]
My problem was that I was using bodyParser to parse request body as json:

`app.use(bodyParser.json());`

If you have an html form and are posting username/password to the server, you need to ask bodyparser to parse urlencoded body:

`app.use(bodyParser.urlencoded({ extended: false }));`

**Comment by pratiktmg19** [comment]
had the same error but now it has fixed..
insetead of just username i have used usernameField

  passport.use(new LocalStrategy({usernameField:'email'},

**Comment by guoxiangke** [comment]
works with 
```
passport.use(new LocalStrategy({
  usernameField: 'user[email]',
  passwordField: 'user[password]',
}, (email, password, done) => {
```
instead of 
```
passport.use(
  new LocalStrategy(async (email: string, password: string, done: Function) => {
    const user: User | null = await User.findOne({ where: { email } })
    if (!user) {
      return done(null, false, { message: 'Incorrect email.' })
    }
    if (user.password !== password) {
      // todo user.validPassword
      return done(null, false, { message: 'Incorrect password.' })
    }
    return done(null, user)
  })
)

```

**Comment by JoakoV3** [comment]
I have the same problem I tried all of this and it's not working. 

`
passport.use(
  new LocalStrategy(
    {
      usernameField: "email",
      passwordField: "password",
    },
    async (email, password, done) => {
      try {
        const user = await Users.findOne({
          where: {
            email,
          },
        });`

**Comment by Nafim-Ershad** [comment]
> works with
> 
> ```
> passport.use(new LocalStrategy({
>   usernameField: 'user[email]',
>   passwordField: 'user[password]',
> }, (email, password, done) => {
> ```
> 
> instead of
> 
> ```
> passport.use(
>   new LocalStrategy(async (email: string, password: string, done: Function) => {
>     const user: User | null = await User.findOne({ where: { email } })
>     if (!user) {
>       return done(null, false, { message: 'Incorrect email.' })
>     }
>     if (user.password !== password) {
>       // todo user.validPassword
>       return done(null, false, { message: 'Incorrect password.' })
>     }
>     return done(null, user)
>   })
> )
> ```

This worked for me, thanks @guoxiangke  😁

**Comment by dnextreme88** [comment]
My problem is the header params that I'm passing to my request when I'm testing this using K6. The original code I used in my script.js:

`const params = { headers: { "Content-Type": "application/json-patch+json", "Accept": "application/json, text/plain, */*" } };`

Changed to:

`const params = { headers: { "Content-Type": "application/json", "Accept": "application/json, text/plain, */*" } };`

**Comment by russell0430** [comment]
i ran into the same problem with the code below .
`const customFields = {
  usenameField: "user",
  passwordField: "pwd",
}`
`const strategy = new LocalStrategy(customFields, verifyCallback)`
and found out that i just misspelled the property 
`usenameField` changed to `usernameField`
